CREATE TABLE tb_proposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor NUMERIC(15, 2) NOT NULL,
    cliente_nome VARCHAR(150) NOT NULL,
    cliente_cpf VARCHAR(14) NOT NULL,
    status VARCHAR(30) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    deletado BOOLEAN NOT NULL DEFAULT FALSE,
    data_exclusao TIMESTAMP
);
