CREATE TABLE tb_contratacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id BIGINT NOT NULL,
    data_contratacao TIMESTAMP NOT NULL,
    deletado BOOLEAN NOT NULL DEFAULT FALSE,
    data_exclusao TIMESTAMP
);
